language: generic
sudo: required
dist: bionic
env:
  - LAZ_VER=2.0.4
os:
  - linux

matrix:
  include:
    - os: linux
      env: LAZ_VER=2.0.4 LAZ_ENV=wine WINEARCH=win32 LAZ_OPT="--os=win32 --cpu=i386"
    - os: linux
      env: LAZ_VER=2.0.4 LAZ_ENV=wine WINEARCH=win64 LAZ_OPT="--os=win64 --cpu=x86_64"
    - os: linux
      env: LAZ_VER=2.0.4 
git:
  depth: 3
before_install:
  - sudo apt-get -y install liblua5.3-0 python3.7
  - export LUAPATH=$(find /usr/ -name liblua5.3.so.0 | sed 's/liblua5.3.so.0//')
  - echo $LUAPATH
  - sudo ln -s $LUAPATH/liblua5.3.so.0 $LUAPATH/liblua5.3.so
install: ./travis-lazarus/.travis.install.py
script:
  - lazbuild $LAZ_OPT kbot6.lpi               # Build my_lazarus_test project
  - $LAZ_ENV ./bin/kbot6 # Run my_lazarus_test testsuite